from enum import Enum

class TeamId(Enum):
    ATLANTA_HAWKS = 1
    BOSTON_CELTICS = 2
    BROOKLYN_NETS = 3
    CHICAGO_BULLS = 4
    CLEVELAND_CAVALIERS = 5
    DALLAS_MAVERICKS = 6
    DENVER_NUGGETS = 7
    DETROIT_PISTONS = 8
    GOLDEN_STATE_WARRIORS = 9
    HOUSTON_ROCKETS = 10
    INDIANA_PACERS = 11
    LOS_ANGELES_CLIPPERS = 12
    LOS_ANGELES_LAKERS = 13
    MEMPHIS_GRIZZLIES = 14
    MIAMI_HEAT = 15
    MILWAUKEE_BUCKS = 16
    MINNESOTA_TIMBERWOLVES = 17
    NEW_ORLEANS_PELICANS = 18
    NEW_YORK_KNICKS = 19
    OKLAHOMA_CITY_THUNDER = 20
    ORLANDO_MAGIC = 21
    PHILADELPHIA_76ERS = 22
    PHOENIX_SUNS = 23
    PORTLAND_TRAIL_BLAZERS = 24
    SACRAMENTO_KINGS = 25
    SAN_ANTONIO_SPURS = 26
    TORONTO_RAPTORS = 27
    UTAH_JAZZ = 28
    WASHINGTON_WIZARDS = 29